# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `fivemat` gem.
# Please instead update this file by running `bin/tapioca gem fivemat`.

module ElapsedTime
  def print_elapsed_time(io, start_time); end
end

module Fivemat
  def initialize(runtime, path_or_io, options); end

  private

  def cucumber3?; end
  def rspec3?; end

  class << self
    def cucumber3?; end
    def new(*args); end
    def rspec3?; end
  end
end

module Fivemat::MiniTest; end

class Fivemat::MiniTest::Unit < ::Minitest::Unit
  include ::ElapsedTime

  def _run_suites(suites, type); end
end

class Fivemat::RSpec < ::RSpec::Core::Formatters::ProgressFormatter
  include ::ElapsedTime

  def initialize(*_arg0); end

  def dump_pending_fixed(example, index); end
  def dump_summary(*_arg0); end
  def example_group_finished(group); end
  def example_group_started(group); end
  def pending_fixed?(example); end
  def start_dump; end
end

class Fivemat::RSpec3
  include ::ElapsedTime

  def initialize(output); end

  def color; end
  def dump_summary(summary); end
  def example_failed(notification); end
  def example_group_finished(event); end
  def example_group_started(event); end
  def example_passed(notification); end
  def example_pending(notification); end
  def failed_notifications; end
  def message(notification); end
  def output; end
  def seed(notification); end
end
