# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `jaro_winkler` gem.
# Please instead update this file by running `bin/tapioca gem jaro_winkler`.

module JaroWinkler
  class << self
    def distance(*_arg0); end
    def jaro_distance(*_arg0); end
  end
end

class JaroWinkler::Error < ::RuntimeError; end
class JaroWinkler::InvalidWeightError < ::JaroWinkler::Error; end
JaroWinkler::VERSION = T.let(T.unsafe(nil), String)
