# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `simplecov-buildkite` gem.
# Please instead update this file by running `bin/tapioca gem simplecov-buildkite`.

module SimpleCov::Buildkite; end

class SimpleCov::Buildkite::AnnotationFormatter
  def format(result); end

  private

  def filter_git_groups(groups); end
  def format_as_metric(name, element, changeset: T.unsafe(nil)); end
  def format_float(float); end
  def format_group(element); end
  def format_integer(integer); end
  def format_line_count(element); end
  def ignore_empty_groups(groups); end
end

SimpleCov::Buildkite::AnnotationFormatter::GIT_ANNOTATION_FORMAT_REGEX = T.let(T.unsafe(nil), Regexp)

module SimpleCov::Buildkite::Profiles
  class << self
    def git(*args); end
    def git_diff_names(*args, diff_filter: T.unsafe(nil)); end
    def git_merge_base(*refs); end
    def git_short_commit(commit); end
    def run(*args); end
  end
end

SimpleCov::Buildkite::VERSION = T.let(T.unsafe(nil), String)
