require:
  - rubocop-rspec
  - rubocop-sorbet
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"

Layout/HashAlignment:
  EnforcedColonStyle:
    - table
    - key
  EnforcedHashRocketStyle:
    - table
    - key

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "Rakefile"
    - "spec/**/*"
    - "Guardfile"

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 6

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rake/Desc:
  Enabled: false

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrivialAccessors:
  AllowPredicates: true

RSpec/ExampleLength:
  Enabled: False

Sorbet/FalseSigil:
  Enabled: True
  Exclude:
    - 'spec/spec_helper.rb'

Sorbet/HasSigil:
  Enabled: True
  Exclude:
    - 'spec/spec_helper.rb'

Sorbet/ValidSigil:
  Enabled: True
  Exclude:
    - 'spec/spec_helper.rb'

Sorbet/StrictSigil:
  Enabled: True
  Exclude:
    - 'spec/**/*'
    - 'lib/fql/version.rb'

Sorbet/ForbidUntypedStructProps:
  Enabled: True
  Exclude:
    - 'lib/fql/query/dsl.rb'

Metrics/CyclomaticComplexity:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'

RSpec/ExpectActual:
  Enabled: true
  Exclude:
    - 'spec/fql/backend/**/*'

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Sorbet/EnforceSignatures:
  Enabled: true
  Exclude:
    - 'Rakefile'

Style/AccessorGrouping:
  Enabled: false

Lint/SuppressedException:
  Enabled: true
  Exclude:
    - 'Rakefile'

RSpec/MultipleExpectations:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/ToJSON:
  Enabled: false
