source "https://rubygems.org"
gemspec

gem "byebug"
gem "fivemat"
gem "guard-rspec"
gem "parlour"
gem "rake", "~> 13.0"
gem "rspec", "~> 3.1.0"
gem "rspec_junit_formatter"
gem "rubocop", "1.24.1"
gem "rubocop-packaging", "0.5.1"
gem "rubocop-performance", "1.14.2"
gem "rubocop-rake", "0.6.0"
gem "rubocop-rspec", "2.7.0"
gem "rubocop-sorbet"
gem "simplecov", require: false
gem "simplecov-buildkite"
gem "solargraph"
gem "sorbet"
gem "sqlite3"
