docker-compose#v3.7.0: &compose_config
  run: app
  config: .buildkite/docker-compose.yaml
steps:
  - label: Sorbet
    command: make sorbet
    agents:
      queue: test
    plugins:
      docker-compose#v3.7.0:
        <<: *compose_config
  - wait
  - label: Lint
    command: make lint
    agents:
      queue: test
    plugins:
      docker-compose#v3.7.0:
        <<: *compose_config
  - label: Test
    command: make test
    agents:
      queue: test
    plugins:
      docker-compose#v3.7.0:
        <<: *compose_config
