docker-compose#v3.7.0: &compose_config
  run: app
  config: .buildkite/docker-compose.yaml
steps:
  - label: Sorbet
    command: srb tc
    agents:
      queue: test
    plugins:
      docker-compose#v3.7.0:
        <<: *compose_config
  - wait
  - label: Lint
    command: rubocop -f emacs -o artifacts/rubocop.txt
    artifact_paths: "artifacts/*"
    agents:
      queue: test
    plugins:
      docker-compose#v3.7.0:
        <<: *compose_config
  - label: Test
    command: sh .buildkite/test.sh
    artifact_paths: "artifacts/*"
    plugins:
      docker-compose#v3.7.0:
        <<: *compose_config
  - wait: ~
    continue_on_failure: true
  - label: Annotate
    plugins:
      - bugcrowd/test-summary#v1.11.0:
          inputs:
            - label: rspec
              artifact_path: artifacts/rspec*
              type: junit
            - label: rubocop
              artifact_path: artifacts/rubocop.txt
              type: oneline
          formatter:
            type: details
          context: test-summary
